### ISSUE TITLE
Errow while uploading photo

### ISSUE THREAD

**Issue by zoltax** [joannamroz/zbook#2]
When I tried to change my avatar, i got and error:

Warning (2): move_uploaded_file(img/avatars/bcb80f03dc6cb8e301481790cab6acc5.jpg): failed to open stream: Permission denied [APP/Controller/UsersController.php, line 200]

Warning (2): move_uploaded_file() [function.move-uploaded-file]: Unable to move '/tmp/phpRpxwmD' to 'img/avatars/bcb80f03dc6cb8e301481790cab6acc5.jpg' [APP/Controller/UsersController.php, line 200]

**Comment by joannamroz** [comment]
Fixed :-P
21 mar 2015 19:11 "zoltax" notifications@github.com napisał(a):

**Comment by zoltax** [comment]
> http://www.easyphp.org/

I don't see any changes :)

**Comment by joannamroz** [comment]
Problem was with file permisions
21 mar 2015 21:03 "zoltax" notifications@github.com napisał(a):

**Comment by zoltax** [comment]
> Problem was with file permisions

I know, but you hadn't committed any changes to the repository :)
Fix in production works perfectly :)
